### ISSUE TITLE
Get all edits for the person with the person id = 92701

### ISSUE THREAD

**Issue by ybressler** [Open-Broadway-Data/MVP-FrontEnd#61]
Write SQL to get all edits for Richard Eye id=92701

Child of #58

**Comment by MelindaSewak** [comment]
```
select *
from broadway.data_edits
where value_primary_id=92701;
```

**Comment by ybressler** [comment]
Need to substitute `value_pre` and `value_post` with actual values.
![Screen Shot 2020-10-27 at 1 48 59 PM](https://user-images.githubusercontent.com/40807730/97341243-2e21f500-185b-11eb-96ef-7675cf88cdd0.png)

**Comment by MelindaSewak** [comment]
Ran into issue with identifying value_pre and value_post - when trying to join data_edits with racial_identity to sub in actual values, only the first of the listed values populates its associated racial identity. Clarified that this field is a comma-separated string and not comma-separated integers (thanks for the heads up, @ybressler !). Working on parsing the values to identify multiple identities - first just with value_pre, then will expand to both value_pre and value_post.

<img width="800" alt="Screen Shot 2020-10-29 at 5 58 41 PM" src="https://user-images.githubusercontent.com/61568976/97641232-69195980-1a10-11eb-87d1-62712f6a0977.png">

**Comment by ybressler** [comment]
I edited the backend server to allow functions to be declared by users.

I'm going to ask that you send me the function you want to create, instead of creating it yourself, being that creation of such functions could have significantly disastrous consequences if not used correctly.

**An example function:**
```
CREATE FUNCTION hello_world (s CHAR(20))
RETURNS char(50) CHARSET latin1
    NO SQL
BEGIN
	RETURN CONCAT('Hello, ',s,'!');
END
```
**Using it:**
```
select broadway.hello_world('Yaakov');

# Returns:
'Hello, Yaakov!'
```

**Comment by MelindaSewak** [comment]
Okay, I have a workable preliminary code to split up the string. Now just need to know what data you want included in the query so I know how to move forward with joining/displaying the edits (will of course expand to include edits outside of race). 

<img width="894" alt="Screen Shot 2020-10-29 at 7 53 22 PM" src="https://user-images.githubusercontent.com/61568976/97647660-d339fa80-1a20-11eb-9cfa-c6b05577f2a0.png">

**Comment by MelindaSewak** [comment]
> I edited the backend server to allow functions to be declared by users.
> 
> I'm going to ask that you send me the function you want to create, instead of creating it yourself, being that creation of such functions could have significantly disastrous consequences if not used correctly.
> 
> **An example function:**
> 
> ```
> CREATE FUNCTION hello_world (s CHAR(20))
> RETURNS char(50) CHARSET latin1
>     NO SQL
> BEGIN
> 	RETURN CONCAT('Hello, ',s,'!');
> END
> ```
> 
> **Using it:**
> 
> ```
> select broadway.hello_world('Yaakov');
> 
> # Returns:
> 'Hello, Yaakov!'
> ```

Ah, just saw this after commenting. That's great! I'll work on this tomorrow and send a function your way.

**Comment by ybressler** [comment]
I'm thinking we should create an additional table for `edit_values` -- which can be a many to one relationship for both `pre` and `post` -- what do you think?

**Comment by ybressler** [comment]
Added 2 new tables to help with arranging these values. Also, will look into creating rich relationships here: https://docs.sqlalchemy.org/en/13/orm/join_conditions.html

**Comment by ybressler** [comment]
I'm going to spend some time today adding methods to the tables created yesterday. If you're around to pair program, that would be cool. But no need. I'll hopefully have completed by EOD.

**Comment by ybressler** [comment]
Also, new ERD

![broadway](https://user-images.githubusercontent.com/40807730/97718327-35841100-1a9c-11eb-857b-bc64af60c543.png)

**Comment by ybressler** [comment]
The table "data edits values" is redundant...

**Comment by ybressler** [comment]
# Backend is fixed!!!

**Comment by ybressler** [comment]
New ERD:

![image](https://user-images.githubusercontent.com/40807730/97932398-e3fab100-1d3d-11eb-9c0f-a4c200aa214c.png)

**Comment by ybressler** [comment]
To make more bite size --> lets begin by getting edits made to a person's racial identity.

**Comment by MelindaSewak** [comment]
This is the general code to get all info for racial identity edits, @ybressler - let me know what specific info you want to include/how you want to parse this down, and I'll edit accordingly:

```
select *
from broadway.data_edits as de
inner join broadway.data_edits_values_link as devl
on de.id=devl.data_edits_id
inner join broadway.data_values as dv
on devl.data_edits_id=dv.id
where de.field='racial_identity';
```

**Comment by ybressler** [comment]
Not quite. Let's start with the following: for each `user_edit_id` I'd like an array of values for pre and post...

**Comment by ybressler** [comment]
Best method forward is to utilize the ORM for this. Will close this issue and re-open when touching on this issue again.
