### ISSUE TITLE
Make input forms a form – not a table...

### ISSUE THREAD

**Issue by ybressler** [Open-Broadway-Data/MVP-FrontEnd#87]
input for the year is floating at the top- we want it to be in the middle. This is due to technical debt that the form is in a table.

**make form a form, not a table**

_Originally posted by @violatido in https://github.com/Open-Broadway-Data/MVP-FrontEnd/issues/85#issuecomment-726831128_

**Comment by ybressler** [comment]
I'll do this on the backend with templates.

@jocelyn-shek Any interest in seeing how this works?

**Comment by jocelyn-shek** [comment]
Yes!

**Comment by ybressler** [comment]
We'll work on this together on our call.

**Comment by ybressler** [comment]
This here in the table / form we want to edit...

![Screen Shot 2020-11-15 at 10 39 18 PM](https://user-images.githubusercontent.com/40807730/99210285-6b5f1000-2793-11eb-9dd9-aedc4f119003.png)

**Comment by ybressler** [comment]
There are 4 forms (Show Genre, Production Type, etc) in a giant wrapped form)
