### ISSUE TITLE
Admin on-click populate on approve form 

### ISSUE THREAD

**Issue by violatido** [Open-Broadway-Data/MVP-FrontEnd#89]
On the admin page, upon clicking a user's row, automatically populate email box at bottom of page and automatically have "approve" or "unapprove" selected based on their status.

**Comment by ybressler** [comment]
This is what the page looks like:
![Screen Shot 2020-11-22 at 6 00 57 PM](https://user-images.githubusercontent.com/40807730/99919645-b37ab700-2cec-11eb-8885-2f297196df47.png)
